insert into softwareengineering.exercise values(0,0,'other');
insert into softwareengineering.exercise values(1,11,'swimming');
insert into softwareengineering.exercise values(2,12,'tennis');
insert into softwareengineering.exercise values(3,13,'running');
insert into softwareengineering.exercise values(4,14,'skipping');
insert into softwareengineering.exercise values(5,15,'rowing');
insert into softwareengineering.exercise values(6,8,'stair machine');
insert into softwareengineering.exercise values(7,10,'stationary cycling');
insert into softwareengineering.exercise values(8,6,'dancing');
insert into softwareengineering.exercise values(9,12,'boxing');
insert into softwareengineering.exercise values(10,14,'skipping');
insert into softwareengineering.exercise values(11,11,'rock climbing');
insert into softwareengineering.exercise values(12,12,'cycling (quick)');
insert into softwareengineering.exercise values(13,9,'golf');
insert into softwareengineering.exercise values(14,10,'hiking');
insert into softwareengineering.exercise values(15,14,'horseriding');
insert into softwareengineering.exercise values(16,6,'walking');
insert into softwareengineering.exercise values(17,12,'ice skating');
insert into softwareengineering.exercise values(18,13,'kayaking');
insert into softwareengineering.exercise values(19,11,'spin cycle');
insert into softwareengineering.exercise values(20,10,'volleyball');
insert into softwareengineering.exercise values(21,8,'weightlifting');
